import { v4 as uuidv4 } from 'uuid';

export interface SeedWord {
  id: string;
  word: string;
  category: string;
  difficulty: 'EASY' | 'MEDIUM' | 'HARD';
  hint: string;
  isActive: boolean;
}

// 210+ curated words with themes, Vietnamese culture, mythological creatures, objects, animals, elements
export const DRAWING_WORDS_SEED: SeedWord[] = [
  // Vietnamese Culture & Heritage (35)
  { id: uuidv4(), word: "Áo dài", category: "Vietnamese Culture", difficulty: "EASY", hint: "Trang phục truyền thống thướt tha của Việt Nam", isActive: true },
  { id: uuidv4(), word: "Nón lá", category: "Vietnamese Culture", difficulty: "EASY", hint: "Vật che nắng mưa hình chóp đan từ lá cọ", isActive: true },
  { id: uuidv4(), word: "Bánh chưng", category: "Vietnamese Culture", difficulty: "EASY", hint: "Món bánh vuông vức gói lá dong ngày Tết", isActive: true },
  { id: uuidv4(), word: "Bánh giầy", category: "Vietnamese Culture", difficulty: "EASY", hint: "Món bánh tròn màu trắng tượng trưng cho trời", isActive: true },
  { id: uuidv4(), word: "Hoa sen", category: "Vietnamese Culture", difficulty: "EASY", hint: "Quốc hoa gần bùn mà chẳng hôi tanh mùi bùn", isActive: true },
  { id: uuidv4(), word: "Cây tre", category: "Vietnamese Culture", difficulty: "EASY", hint: "Cây thân đốt dẻo dai biểu tượng làng quê Việt", isActive: true },
  { id: uuidv4(), word: "Trống đồng", category: "Vietnamese Culture", difficulty: "HARD", hint: "Cổ vật Đông Sơn với hoa văn ngôi sao và chim lạc", isActive: true },
  { id: uuidv4(), word: "Chùa Một Cột", category: "Vietnamese Culture", difficulty: "HARD", hint: "Ngôi chùa độc đáo tọa lạc trên một cột đá ở Hà Nội", isActive: true },
  { id: uuidv4(), word: "Tháp Rùa", category: "Vietnamese Culture", difficulty: "MEDIUM", hint: "Công trình cổ kính nằm giữa hồ Hoàn Kiếm", isActive: true },
  { id: uuidv4(), word: "Cầu Rồng", category: "Vietnamese Culture", difficulty: "MEDIUM", hint: "Cây cầu bắc qua sông Hàn có khả năng phun lửa", isActive: true },
  { id: uuidv4(), word: "Đèn lồng Hội An", category: "Vietnamese Culture", difficulty: "MEDIUM", hint: "Đèn giấy lụa rực rỡ phố cổ ven sông Hoài", isActive: true },
  { id: uuidv4(), word: "Bát phở", category: "Vietnamese Culture", difficulty: "EASY", hint: "Món ăn quốc hồn quốc túy với nước dùng đậm đà", isActive: true },
  { id: uuidv4(), word: "Bánh mì", category: "Vietnamese Culture", difficulty: "EASY", hint: "Món ăn đường phố giòn rụm kẹp thịt pa-tê", isActive: true },
  { id: uuidv4(), word: "Cà phê phin", category: "Vietnamese Culture", difficulty: "EASY", hint: "Thức uống từng giọt đắng ngắt bên đá ngọt ngào", isActive: true },
  { id: uuidv4(), word: "Chợ Bến Thành", category: "Vietnamese Culture", difficulty: "HARD", hint: "Khu chợ biểu tượng Sài Gòn với đồng hồ bốn mặt", isActive: true },
  { id: uuidv4(), word: "Đàn bầu", category: "Vietnamese Culture", difficulty: "MEDIUM", hint: "Nhạc cụ dân tộc độc đáo chỉ có một dây", isActive: true },
  { id: uuidv4(), word: "Quạt giấy", category: "Vietnamese Culture", difficulty: "EASY", hint: "Dụng cụ phe phẩy nan tre giấy bồi tạo gió", isActive: true },
  { id: uuidv4(), word: "Múa lân", category: "Vietnamese Culture", difficulty: "MEDIUM", hint: "Điệu múa rộn ràng mừng Tết và Trung Thu", isActive: true },
  { id: uuidv4(), word: "Đầu lân", category: "Vietnamese Culture", difficulty: "MEDIUM", hint: "Chiếc đầu sặc sỡ nhấp nháy mắt trong hội múa", isActive: true },
  { id: uuidv4(), word: "Pháo hoa", category: "Vietnamese Culture", difficulty: "EASY", hint: "Ánh sáng rực rỡ tỏa sáng bầu trời đêm giao thừa", isActive: true },
  { id: uuidv4(), word: "Bao lì xì", category: "Vietnamese Culture", difficulty: "EASY", hint: "Phong bao đỏ thắm mang may mắn đầu xuân", isActive: true },
  { id: uuidv4(), word: "Hoa đào", category: "Vietnamese Culture", difficulty: "EASY", hint: "Loài hoa sắc hồng rực rỡ đón xuân miền Bắc", isActive: true },
  { id: uuidv4(), word: "Hoa mai", category: "Vietnamese Culture", difficulty: "EASY", hint: "Sắc vàng hoa Tết phương Nam khoe sắc", isActive: true },
  { id: uuidv4(), word: "Mâm ngũ quả", category: "Vietnamese Culture", difficulty: "MEDIUM", hint: "Mâm trái cây dâng cúng tổ tiên ngày Tết", isActive: true },
  { id: uuidv4(), word: "Bến Nhà Rồng", category: "Vietnamese Culture", difficulty: "HARD", hint: "Nơi Bác Hồ ra đi tìm đường cứu nước", isActive: true },
  { id: uuidv4(), word: "Thuyền thúng", category: "Vietnamese Culture", difficulty: "MEDIUM", hint: "Chiếc thuyền tròn độc đáo của ngư dân biển", isActive: true },
  { id: uuidv4(), word: "Cột cờ Lũng Cú", category: "Vietnamese Culture", difficulty: "HARD", hint: "Điểm cực Bắc thiêng liêng trên đỉnh núi", isActive: true },
  { id: uuidv4(), word: "Tò he", category: "Vietnamese Culture", difficulty: "MEDIUM", hint: "Đồ chơi dân gian nặn từ bột màu ăn được", isActive: true },
  { id: uuidv4(), word: "Trầu cau", category: "Vietnamese Culture", difficulty: "MEDIUM", hint: "Miếng trầu là đầu câu chuyện cưới hỏi", isActive: true },
  { id: uuidv4(), word: "Xe xích lô", category: "Vietnamese Culture", difficulty: "MEDIUM", hint: "Phương tiện ba bánh chở khách ngắm phố phường", isActive: true },
  { id: uuidv4(), word: "Cổng làng", category: "Vietnamese Culture", difficulty: "MEDIUM", hint: "Cửa ngõ mái ngói rêu phong của làng quê", isActive: true },
  { id: uuidv4(), word: "Cánh diều", category: "Vietnamese Culture", difficulty: "EASY", hint: "Vật bay lượn vi vu trên triền đê lộng gió", isActive: true },
  { id: uuidv4(), word: "Đèn ông sao", category: "Vietnamese Culture", difficulty: "EASY", hint: "Chiếc đèn năm cánh lấp lánh rước đêm trăng rằm", isActive: true },
  { id: uuidv4(), word: "Bánh trung thu", category: "Vietnamese Culture", difficulty: "EASY", hint: "Chiếc bánh nướng/dẻo ngắm trăng tròn rằm tháng Tám", isActive: true },
  { id: uuidv4(), word: "Rùa vàng", category: "Vietnamese Culture", difficulty: "MEDIUM", hint: "Linh vật hoàn gươm thần cho vua Lê Lợi", isActive: true },

  // Mythological & Fantasy Spirits (35)
  { id: uuidv4(), word: "Rồng Lửa", category: "Mythology", difficulty: "MEDIUM", hint: "Sinh vật huyền thoại uy mãnh thở ra ngọn lửa thiêng", isActive: true },
  { id: uuidv4(), word: "Phượng Hoàng", category: "Mythology", difficulty: "HARD", hint: "Loài chim bất tử tái sinh từ tro tàn", isActive: true },
  { id: uuidv4(), word: "Kỳ Lân", category: "Mythology", difficulty: "HARD", hint: "Linh thú nhân từ mang sừng thần và vảy rồng", isActive: true },
  { id: uuidv4(), word: "Hồ Ly 9 Đuôi", category: "Mythology", difficulty: "HARD", hint: "Yêu linh cáo chín đuôi biến hóa kỳ ảo", isActive: true },
  { id: uuidv4(), word: "Thần Sấm", category: "Mythology", difficulty: "MEDIUM", hint: "Vị thần tay cầm búa giáng thiên lôi chớp giật", isActive: true },
  { id: uuidv4(), word: "Sơn Tinh", category: "Mythology", difficulty: "MEDIUM", hint: "Chúa tể non cao dời non lấp biển", isActive: true },
  { id: uuidv4(), word: "Thủy Tinh", category: "Mythology", difficulty: "MEDIUM", hint: "Chúa tể biển cả hô mưa gọi gió dâng sóng thần", isActive: true },
  { id: uuidv4(), word: "Thạch Sanh", category: "Mythology", difficulty: "MEDIUM", hint: "Dũng sĩ chém Chằn tinh giải cứu công chúa", isActive: true },
  { id: uuidv4(), word: "Gươm Thần", category: "Mythology", difficulty: "MEDIUM", hint: "Thanh bảo kiếm Thuận Thiên phát sáng kỳ bí", isActive: true },
  { id: uuidv4(), word: "Ngọc Hoàng", category: "Mythology", difficulty: "HARD", hint: "Đấng tối cao cai quản Thiên đình", isActive: true },
  { id: uuidv4(), word: "Cá Chép Hóa Rồng", category: "Mythology", difficulty: "HARD", hint: "Cá vượt vũ môn biến hóa râu dài bay lượn", isActive: true },
  { id: uuidv4(), word: "Bạch Hổ", category: "Mythology", difficulty: "MEDIUM", hint: "Hổ trắng uy phong trấn giữ phương Tây", isActive: true },
  { id: uuidv4(), word: "Huyền Vũ", category: "Mythology", difficulty: "HARD", hint: "Linh thú kết hợp giữa rùa đen và rắn quấn quanh", isActive: true },
  { id: uuidv4(), word: "Thanh Long", category: "Mythology", difficulty: "MEDIUM", hint: "Rồng xanh uy dũng hộ vệ phương Đông", isActive: true },
  { id: uuidv4(), word: "Chu Tước", category: "Mythology", difficulty: "MEDIUM", hint: "Chim lửa rực rỡ phương Nam", isActive: true },
  { id: uuidv4(), word: "Cây Gậy Thần", category: "Mythology", difficulty: "EASY", hint: "Bảo vật Chử Đồng Tử cắm xuống hóa lâu đài", isActive: true },
  { id: uuidv4(), word: "Chiếc Nón Thần", category: "Mythology", difficulty: "EASY", hint: "Chiếc nón phép nhiệm màu của Tiên Dung", isActive: true },
  { id: uuidv4(), word: "Nỏ Thần", category: "Mythology", difficulty: "MEDIUM", hint: "Vũ khí bắn một phát vạn mũi tên của An Dương Vương", isActive: true },
  { id: uuidv4(), word: "Móng Rùa Vàng", category: "Mythology", difficulty: "MEDIUM", hint: "Vật báu làm lẫy nỏ giữ yên bờ cõi", isActive: true },
  { id: uuidv4(), word: "Cây Đa Chú Cuội", category: "Mythology", difficulty: "MEDIUM", hint: "Cây cổ thụ bay lên cung trăng cùng chú Cuội", isActive: true },
  { id: uuidv4(), word: "Chị Hằng Nga", category: "Mythology", difficulty: "MEDIUM", hint: "Nàng tiên kiều diễm ngự trên cung trăng", isActive: true },
  { id: uuidv4(), word: "Thỏ Ngọc", category: "Mythology", difficulty: "EASY", hint: "Chú thỏ trắng giã thuốc trường sinh cung Quảng Hàn", isActive: true },
  { id: uuidv4(), word: "Ngựa Gióng", category: "Mythology", difficulty: "MEDIUM", hint: "Ngựa sắt phun lửa cùng Thánh Gióng dẹp giặc Ân", isActive: true },
  { id: uuidv4(), word: "Bụi Tre Ngà", category: "Mythology", difficulty: "MEDIUM", hint: "Vũ khí Thánh Gióng nhổ bên đường quất tan quân thù", isActive: true },
  { id: uuidv4(), word: "Chim Lạc", category: "Mythology", difficulty: "MEDIUM", hint: "Cánh chim huyền sử sải cánh trên mặt trống đồng", isActive: true },
  { id: uuidv4(), word: "Hạc Cưỡi Rùa", category: "Mythology", difficulty: "HARD", hint: "Hình tượng linh thiêng thường đặt nơi chốn đình chùa", isActive: true },
  { id: uuidv4(), word: "Ông Táo", category: "Mythology", difficulty: "MEDIUM", hint: "Thần bếp cưỡi cá chép về trời ngày 23 tháng Chạp", isActive: true },
  { id: uuidv4(), word: "Cây Nêu", category: "Mythology", difficulty: "MEDIUM", hint: "Cây tre treo chuông khánh trừ tà ngày giáp Tết", isActive: true },
  { id: uuidv4(), word: "Thần Đèn", category: "Mythology", difficulty: "EASY", hint: "Linh thần bước ra từ làn khói chiếc đèn cổ", isActive: true },
  { id: uuidv4(), word: "Thảm Bay", category: "Mythology", difficulty: "EASY", hint: "Tấm thảm ma thuật lơ lửng trên không trung", isActive: true },
  { id: uuidv4(), word: "Người Cá", category: "Mythology", difficulty: "MEDIUM", hint: "Mỹ nhân nửa người nửa đuôi cá bơi lội biển sâu", isActive: true },
  { id: uuidv4(), word: "Nhân Mã", category: "Mythology", difficulty: "MEDIUM", hint: "Chiến binh nửa thân người nửa thân ngựa bắn cung", isActive: true },
  { id: uuidv4(), word: "Cánh Cổng Thứ Nguyên", category: "Mythology", difficulty: "HARD", hint: "Vòng xoáy ánh sáng dẫn sang thế giới linh thú", isActive: true },
  { id: uuidv4(), word: "Viên Ngọc Rồng", category: "Mythology", difficulty: "MEDIUM", hint: "Hạt ngọc tỏa hào quang chứa nguồn năng lượng vô tận", isActive: true },
  { id: uuidv4(), word: "Cung Tên Thần", category: "Mythology", difficulty: "MEDIUM", hint: "Cây cung bắn ra mũi tên ánh sáng lấp lánh", isActive: true },

  // Nature & Elements (35)
  { id: uuidv4(), word: "Ngọn Lửa", category: "Elements", difficulty: "EASY", hint: "Ngọn lửa bập bùng tỏa hơi ấm và ánh sáng", isActive: true },
  { id: uuidv4(), word: "Giọt Nước", category: "Elements", difficulty: "EASY", hint: "Hạt sương mai óng ánh rơi xuống mặt hồ", isActive: true },
  { id: uuidv4(), word: "Tia Chớp", category: "Elements", difficulty: "EASY", hint: "Đường zig-zag lóe sáng xé toạc bầu trời giông bão", isActive: true },
  { id: uuidv4(), word: "Lốc Xoáy", category: "Elements", difficulty: "MEDIUM", hint: "Cơn gió xoáy hình phễu khổng lồ cuốn phăng mặt đất", isActive: true },
  { id: uuidv4(), word: "Núi Băng", category: "Elements", difficulty: "MEDIUM", hint: "Khối băng trắng xóa trôi nổi nơi bắc cực giá lạnh", isActive: true },
  { id: uuidv4(), word: "Cầu Vồng", category: "Elements", difficulty: "EASY", hint: "Dải bảy sắc rực rỡ vắt ngang trời sau cơn mưa", isActive: true },
  { id: uuidv4(), word: "Mặt Trời", category: "Elements", difficulty: "EASY", hint: "Quả cầu lửa ban phát sự sống cho toàn vũ trụ", isActive: true },
  { id: uuidv4(), word: "Mặt Trăng", category: "Elements", difficulty: "EASY", hint: "Vầng sáng dịu êm soi tỏ màn đêm tĩnh mịch", isActive: true },
  { id: uuidv4(), word: "Thiên Thạch", category: "Elements", difficulty: "MEDIUM", hint: "Hòn đá bốc cháy từ vũ trụ lao xuống bầu khí quyển", isActive: true },
  { id: uuidv4(), word: "Sóng Thần", category: "Elements", difficulty: "MEDIUM", hint: "Bức tường nước cuồn cuộn dâng cao ập vào bờ biển", isActive: true },
  { id: uuidv4(), word: "Hang Động", category: "Elements", difficulty: "MEDIUM", hint: "Lòng núi sâu thẳm rợp bóng nhũ đá lung linh", isActive: true },
  { id: uuidv4(), word: "Thác Nước", category: "Elements", difficulty: "MEDIUM", hint: "Dòng nước đổ từ vách đá cao bọt tung trắng xóa", isActive: true },
  { id: uuidv4(), word: "Rừng Rậm", category: "Elements", difficulty: "MEDIUM", hint: "Thảm thực vật xanh rì rậm rạp dây leo chằng chịt", isActive: true },
  { id: uuidv4(), word: "Sa Mạc", category: "Elements", difficulty: "MEDIUM", hint: "Vùng đất cằn cỗi mênh mông cát vàng và xương rồng", isActive: true },
  { id: uuidv4(), word: "Núi Lửa", category: "Elements", difficulty: "MEDIUM", hint: "Ngọn núi đang sôi trào nham thạch đỏ rực phun khói", isActive: true },
  { id: uuidv4(), word: "Đám Mây", category: "Elements", difficulty: "EASY", hint: "Bông xốp bồng bềnh trôi trên nền trời xanh biếc", isActive: true },
  { id: uuidv4(), word: "Bông Tuyết", category: "Elements", difficulty: "EASY", hint: "Tinh thể băng sáu cánh rơi nhẹ nhàng mùa đông", isActive: true },
  { id: uuidv4(), word: "Đêm Đầy Sao", category: "Elements", difficulty: "MEDIUM", hint: "Bầu trời đêm lấp lánh muôn ngàn đốm sáng", isActive: true },
  { id: uuidv4(), word: "Hố Đen", category: "Elements", difficulty: "HARD", hint: "Vùng không gian kỳ dị hút cả ánh sáng vào tâm", isActive: true },
  { id: uuidv4(), word: "Cực Quang", category: "Elements", difficulty: "HARD", hint: "Màn lụa ánh sáng xanh tím uốn lượn vùng địa cực", isActive: true },
  { id: uuidv4(), word: "Sao Băng", category: "Elements", difficulty: "EASY", hint: "Vệt sáng xẹt ngang đêm hè để người ta ước nguyện", isActive: true },
  { id: uuidv4(), word: "Cơn Mưa", category: "Elements", difficulty: "EASY", hint: "Từng hạt nước tí tách rơi từ những đám mây xám", isActive: true },
  { id: uuidv4(), word: "Sương Mù", category: "Elements", difficulty: "MEDIUM", hint: "Lớp hơi nước bảng lảng mờ ảo bao phủ cảnh vật", isActive: true },
  { id: uuidv4(), word: "Hồ Nước", category: "Elements", difficulty: "EASY", hint: "Mặt nước phẳng lặng như gương phản chiếu mây trời", isActive: true },
  { id: uuidv4(), word: "Đảo Hoang", category: "Elements", difficulty: "MEDIUM", hint: "Vùng đất nhỏ giữa đại dương chỉ có cây dừa và cát", isActive: true },
  { id: uuidv4(), word: "Cánh Đồng Lúa", category: "Elements", difficulty: "MEDIUM", hint: "Thảm vàng óng ả hương thơm hạt ngọc quê hương", isActive: true },
  { id: uuidv4(), word: "Hoa Hướng Dương", category: "Elements", difficulty: "EASY", hint: "Loài hoa luôn hướng về phía ánh mặt trời ấm áp", isActive: true },
  { id: uuidv4(), word: "Cây Xương Rồng", category: "Elements", difficulty: "EASY", hint: "Loài cây đầy gai nhọn kiên cường sống giữa cát khô", isActive: true },
  { id: uuidv4(), word: "Cây Nấm", category: "Elements", difficulty: "EASY", hint: "Chiếc ô nhỏ xinh mọc lên từ đất ẩm sau mưa", isActive: true },
  { id: uuidv4(), word: "Lá Phong Đỏ", category: "Elements", difficulty: "EASY", hint: "Chiếc lá hình bàn tay ngả màu đỏ rực mùa thu", isActive: true },
  { id: uuidv4(), word: "Rạn San Hô", category: "Elements", difficulty: "HARD", hint: "Khu vườn kỳ thú sặc sỡ dưới đáy biển xanh", isActive: true },
  { id: uuidv4(), word: "Ngọn Hải Đăng", category: "Elements", difficulty: "MEDIUM", hint: "Tháp đèn dẫn đường cho tàu thuyền đêm tối", isActive: true },
  { id: uuidv4(), word: "Vực Sâu", category: "Elements", difficulty: "MEDIUM", hint: "Khe nứt sâu thẳm ngăn cách hai vách đá dựng đứng", isActive: true },
  { id: uuidv4(), word: "Hòn Trống Mái", category: "Elements", difficulty: "HARD", hint: "Hai khối đá tự nhiên biểu tượng vịnh Hạ Long", isActive: true },
  { id: uuidv4(), word: "Rừng Ngập Mặn", category: "Elements", difficulty: "HARD", hint: "Rừng cây rễ chằng chịt bám sâu trong bãi bồi sú vẹt", isActive: true },

  // Animals (35)
  { id: uuidv4(), word: "Con Hổ", category: "Animals", difficulty: "EASY", hint: "Chúa sơn lâm với bộ lông vằn đen cam oai vệ", isActive: true },
  { id: uuidv4(), word: "Sư Tử", category: "Animals", difficulty: "EASY", hint: "Vua đồng cỏ với chiếc bờm xù dũng mãnh", isActive: true },
  { id: uuidv4(), word: "Voi", category: "Animals", difficulty: "EASY", hint: "Loài vật khổng lồ có vòi dài và đôi ngà trắng", isActive: true },
  { id: uuidv4(), word: "Hươu Cao Cổ", category: "Animals", difficulty: "EASY", hint: "Loài thú có chiếc cổ dài lênh khênh ăn lá trên cao", isActive: true },
  { id: uuidv4(), word: "Gấu Trúc", category: "Animals", difficulty: "EASY", hint: "Chú gấu khoang trắng đen đáng yêu mê ăn trúc", isActive: true },
  { id: uuidv4(), word: "Chim Cánh Cụt", category: "Animals", difficulty: "EASY", hint: "Loài chim mặc áo tuxedo lạch bạch trên băng tuyết", isActive: true },
  { id: uuidv4(), word: "Cá Heo", category: "Animals", difficulty: "EASY", hint: "Loài vật biển thông minh hay nhảy múa trên sóng", isActive: true },
  { id: uuidv4(), word: "Cá Voi Xanh", category: "Animals", difficulty: "MEDIUM", hint: "Sinh vật to lớn nhất hành tinh bơi lội đại dương", isActive: true },
  { id: uuidv4(), word: "Bạch Tuộc", category: "Animals", difficulty: "EASY", hint: "Sinh vật mềm có 8 xúc tua và túi mực tự vệ", isActive: true },
  { id: uuidv4(), word: "Cua Biển", category: "Animals", difficulty: "EASY", hint: "Chú giáp xác có đôi càng to bò ngang trên cát", isActive: true },
  { id: uuidv4(), word: "Đại Bàng", category: "Animals", difficulty: "MEDIUM", hint: "Chúa tể bầu trời với móng vuốt sắc và ánh mắt tinh", isActive: true },
  { id: uuidv4(), word: "Cú Mèo", category: "Animals", difficulty: "EASY", hint: "Loài chim thức đêm với đôi mắt to tròn xoay đầu 270 độ", isActive: true },
  { id: uuidv4(), word: "Sóc Chuột", category: "Animals", difficulty: "EASY", hint: "Chú bé nhỏ nhắn tha hạt dẻ nhét đầy hai bên má", isActive: true },
  { id: uuidv4(), word: "Chó Sói", category: "Animals", difficulty: "MEDIUM", hint: "Kẻ săn mồi hoang dã cất tiếng hú dưới ánh trăng tròn", isActive: true },
  { id: uuidv4(), word: "Tắc Kè Hoa", category: "Animals", difficulty: "MEDIUM", hint: "Bậc thầy ngụy trang thay đổi màu da theo môi trường", isActive: true },
  { id: uuidv4(), word: "Con Rùa", category: "Animals", difficulty: "EASY", hint: "Sinh vật chậm chạp mang chiếc mai cứng cáp trên lưng", isActive: true },
  { id: uuidv4(), word: "Chim Ruồi", category: "Animals", difficulty: "MEDIUM", hint: "Loài chim tí hon vỗ cánh nhanh thoăn thoắt hút mật", isActive: true },
  { id: uuidv4(), word: "Chuồn Chuồn", category: "Animals", difficulty: "EASY", hint: "Côn trùng bốn cánh mỏng manh bay là là báo mưa nắng", isActive: true },
  { id: uuidv4(), word: "Đom Đóm", category: "Animals", difficulty: "EASY", hint: "Chú bọ phát ra ánh sáng lập lòe trong đêm tối", isActive: true },
  { id: uuidv4(), word: "Bướm Đêm", category: "Animals", difficulty: "EASY", hint: "Côn trùng cánh phấn hay lao vào ánh đèn", isActive: true },
  { id: uuidv4(), word: "Con Ngựa", category: "Animals", difficulty: "EASY", hint: "Loài vật bờm dài phi nước đại trên thảo nguyên", isActive: true },
  { id: uuidv4(), word: "Con Trâu", category: "Animals", difficulty: "EASY", hint: "Đầu cơ nghiệp của người nông dân Việt Nam", isActive: true },
  { id: uuidv4(), word: "Con Mèo", category: "Animals", difficulty: "EASY", hint: "Thú cưng bốn chân kêu meo meo thích bắt chuột", isActive: true },
  { id: uuidv4(), word: "Con Chó", category: "Animals", difficulty: "EASY", hint: "Người bạn trung thành vẫy đuôi mừng chủ về", isActive: true },
  { id: uuidv4(), word: "Con Cáo", category: "Animals", difficulty: "MEDIUM", hint: "Loài thú lông đỏ ranh mãnh đuôi xù", isActive: true },
  { id: uuidv4(), word: "Nhện Giăng Tơ", category: "Animals", difficulty: "EASY", hint: "Sinh vật 8 chân dệt mạng lưới tinh xảo bẫy mồi", isActive: true },
  { id: uuidv4(), word: "Bọ Ngựa", category: "Animals", difficulty: "MEDIUM", hint: "Võ sĩ xanh với đôi kiếm răng cưa phía trước", isActive: true },
  { id: uuidv4(), word: "Con Ong Mật", category: "Animals", difficulty: "EASY", hint: "Thợ cần cù chăm chỉ hút nhụy hoa làm mật ngọt", isActive: true },
  { id: uuidv4(), word: "Con Kiến", category: "Animals", difficulty: "EASY", hint: "Đoàn quân tí hon tha mồi về tổ có kỷ luật cao", isActive: true },
  { id: uuidv4(), word: "Cá Ngựa", category: "Animals", difficulty: "MEDIUM", hint: "Loài cá kỳ lạ có đầu giống ngựa bơi thẳng đứng", isActive: true },
  { id: uuidv4(), word: "Sứa Biển", category: "Animals", difficulty: "EASY", hint: "Chiếc dù trong suốt dập dềnh phát sáng dưới biển", isActive: true },
  { id: uuidv4(), word: "Hải Cẩu", category: "Animals", difficulty: "EASY", hint: "Chú thú biển mũm mĩm vỗ vây tung hứng bóng", isActive: true },
  { id: uuidv4(), word: "Gấu Bắc Cực", category: "Animals", difficulty: "EASY", hint: "Bộ lông dày trắng như tuyết sưởi ấm giữa giá băng", isActive: true },
  { id: uuidv4(), word: "Canguru", category: "Animals", difficulty: "EASY", hint: "Loài thú nhảy bằng hai chân sau có túi nuôi con", isActive: true },
  { id: uuidv4(), word: "Gấu Koala", category: "Animals", difficulty: "EASY", hint: "Chú gấu túi dễ thương ôm chặt thân cây khuynh diệp ngủ", isActive: true },

  // Everyday Objects & Tools (35)
  { id: uuidv4(), word: "Chiếc Đồng Hồ", category: "Objects", difficulty: "EASY", hint: "Vật đếm từng giây từng phút chuyển động vòng tròn", isActive: true },
  { id: uuidv4(), word: "Kính Lúp", category: "Objects", difficulty: "EASY", hint: "Dụng cụ thấu kính phóng to mọi chi tiết nhỏ bé", isActive: true },
  { id: uuidv4(), word: "Kính Viễn Vọng", category: "Objects", difficulty: "MEDIUM", hint: "Ống nhòm tầm xa để ngắm các vì sao xa xôi", isActive: true },
  { id: uuidv4(), word: "La Bàn", category: "Objects", difficulty: "EASY", hint: "Kim từ tính luôn chỉ về hướng Bắc giúp định vị", isActive: true },
  { id: uuidv4(), word: "Bản Đồ Kho Báu", category: "Objects", difficulty: "MEDIUM", hint: "Tấm da dê vẽ hải trình đánh dấu chữ X bí ẩn", isActive: true },
  { id: uuidv4(), word: "Rương Gỗ", category: "Objects", difficulty: "EASY", hint: "Chiếc hòm nạm đồng đựng đầy vàng bạc châu báu", isActive: true },
  { id: uuidv4(), word: "Chìa Khóa Vàng", category: "Objects", difficulty: "EASY", hint: "Vật mở cánh cổng kho báu hoặc bí mật cổ xưa", isActive: true },
  { id: uuidv4(), word: "Quyển Sách Cổ", category: "Objects", difficulty: "EASY", hint: "Cuốn sách bìa da dày cộp chứa kiến thức nghìn năm", isActive: true },
  { id: uuidv4(), word: "Bút Lông", category: "Objects", difficulty: "EASY", hint: "Dụng cụ chấm mực tàu viết chữ thư pháp", isActive: true },
  { id: uuidv4(), word: "Nghiên Mực", category: "Objects", difficulty: "MEDIUM", hint: "Khối đá mài mực đen để viết câu đối", isActive: true },
  { id: uuidv4(), word: "Cây Đàn Guitar", category: "Objects", difficulty: "EASY", hint: "Nhạc cụ sáu dây thùng gỗ gảy nên khúc tình ca", isActive: true },
  { id: uuidv4(), word: "Kính Râm", category: "Objects", difficulty: "EASY", hint: "Cặp mắt kính màu tối che mắt khỏi ánh nắng chói chang", isActive: true },
  { id: uuidv4(), word: "Tai Nghe", category: "Objects", difficulty: "EASY", hint: "Thiết bị chụp tai để đắm chìm vào thế giới âm nhạc", isActive: true },
  { id: uuidv4(), word: "Máy Ảnh", category: "Objects", difficulty: "EASY", hint: "Chiếc hộp bấm tách một cái lưu giữ khoảnh khắc", isActive: true },
  { id: uuidv4(), word: "Chiếc Ô", category: "Objects", difficulty: "EASY", hint: "Mái che xòe ra che nắng che mưa cho người đi bộ", isActive: true },
  { id: uuidv4(), word: "Ngọn Nến", category: "Objects", difficulty: "EASY", hint: "Thỏi sáp thắp lên ánh lửa lung linh ấm áp", isActive: true },
  { id: uuidv4(), word: "Đèn Bão", category: "Objects", difficulty: "MEDIUM", hint: "Chiếc đèn dầu lồng kính chống gió của thủy thủ", isActive: true },
  { id: uuidv4(), word: "Chiếc Mỏ Neo", category: "Objects", difficulty: "EASY", hint: "Khối sắt nặng thả xuống đáy giữ thuyền đứng yên", isActive: true },
  { id: uuidv4(), word: "Bánh Lái Thuyền", category: "Objects", difficulty: "MEDIUM", hint: "Bánh gỗ có các tay nắm điều khiển hướng tàu đi", isActive: true },
  { id: uuidv4(), word: "Bình Gốm", category: "Objects", difficulty: "EASY", hint: "Đồ gốm nung men xanh cắm hoa trang trí", isActive: true },
  { id: uuidv4(), word: "Chiếc Búa", category: "Objects", difficulty: "EASY", hint: "Dụng cụ đầu kim loại đóng đinh vào gỗ chắc nịch", isActive: true },
  { id: uuidv4(), word: "Cái Kéo", category: "Objects", difficulty: "EASY", hint: "Dụng cụ hai lưỡi sắc bén cắt giấy và vải", isActive: true },
  { id: uuidv4(), word: "Chiếc Ba Lô", category: "Objects", difficulty: "EASY", hint: "Túi đựng hành lý đeo sau lưng trên mọi nẻo đường", isActive: true },
  { id: uuidv4(), word: "Bình Giữ Nhiệt", category: "Objects", difficulty: "EASY", hint: "Chiếc bình giữ nước nóng hoặc lạnh suốt cả ngày", isActive: true },
  { id: uuidv4(), word: "Đôi Giày Thể Thao", category: "Objects", difficulty: "EASY", hint: "Đôi giày đế cao su êm ái cho những bước chạy nhanh", isActive: true },
  { id: uuidv4(), word: "Quả Bóng Đá", category: "Objects", difficulty: "EASY", hint: "Trái bóng tròn lăn trên sân cỏ của môn thể thao vua", isActive: true },
  { id: uuidv4(), word: "Vương Miện", category: "Objects", difficulty: "MEDIUM", hint: "Mũ miện nạm kim cương dành cho đức vua hoặc nữ hoàng", isActive: true },
  { id: uuidv4(), word: "Khiên Chắn", category: "Objects", difficulty: "EASY", hint: "Vũ khí phòng thủ bản to đỡ các đòn tấn công", isActive: true },
  { id: uuidv4(), word: "Mũ Giáp Sắt", category: "Objects", difficulty: "MEDIUM", hint: "Mũ che đầu bảo vệ chiến binh nơi chiến trận", isActive: true },
  { id: uuidv4(), word: "Lọ Độc Dược", category: "Objects", difficulty: "MEDIUM", hint: "Bình thủy tinh sủi bọt khói tím kỳ dị của phù thủy", isActive: true },
  { id: uuidv4(), word: "Chiếc Đồng Hồ Cát", category: "Objects", difficulty: "EASY", hint: "Bình thủy tinh hai đầu để cát chảy đo thời gian", isActive: true },
  { id: uuidv4(), word: "Chuông Gió", category: "Objects", difficulty: "EASY", hint: "Thanh kim loại leng keng vui tai mỗi khi gió lùa", isActive: true },
  { id: uuidv4(), word: "Bình Tưới Cây", category: "Objects", difficulty: "EASY", hint: "Chiếc vòi hoa sen tưới mát cho những luống hoa", isActive: true },
  { id: uuidv4(), word: "Bức Tranh Vẽ", category: "Objects", difficulty: "EASY", hint: "Tác phẩm nghệ thuật đóng khung treo trên tường", isActive: true },
  { id: uuidv4(), word: "Đôi Đũa", category: "Objects", difficulty: "EASY", hint: "Cặp que song hành gắp thức ăn trong bữa cơm Á Đông", isActive: true },

  // World Landmarks & Fantasy Architecture (35)
  { id: uuidv4(), word: "Kim Tự Tháp", category: "Landmarks", difficulty: "EASY", hint: "Công trình đá khổng lồ hình tam giác ở Ai Cập", isActive: true },
  { id: uuidv4(), word: "Vạn Lý Trường Thành", category: "Landmarks", difficulty: "HARD", hint: "Bức tường thành dài vạn dặm uốn lượn qua các dãy núi", isActive: true },
  { id: uuidv4(), word: "Tháp Eiffel", category: "Landmarks", difficulty: "EASY", hint: "Ngọn tháp thép biểu tượng của thủ đô Paris nước Pháp", isActive: true },
  { id: uuidv4(), word: "Tượng Nữ Thần Tự Do", category: "Landmarks", difficulty: "HARD", hint: "Bức tượng cầm đuốc soi đường ở vịnh New York", isActive: true },
  { id: uuidv4(), word: "Đấu Trường La Mã", category: "Landmarks", difficulty: "HARD", hint: "Công trình vòng cung cổ đại nơi diễn ra các trận giác đấu", isActive: true },
  { id: uuidv4(), word: "Đền Taj Mahal", category: "Landmarks", difficulty: "HARD", hint: "Lăng mộ đá cẩm thạch trắng tráng lệ ở Ấn Độ", isActive: true },
  { id: uuidv4(), word: "Núi Phú Sĩ", category: "Landmarks", difficulty: "MEDIUM", hint: "Ngọn núi tuyết phủ quanh năm biểu tượng Nhật Bản", isActive: true },
  { id: uuidv4(), word: "Nhà Hát Con Sò", category: "Landmarks", difficulty: "MEDIUM", hint: "Công trình mái vòm hình cánh buồm ở Sydney nước Úc", isActive: true },
  { id: uuidv4(), word: "Tháp Nghiêng Pisa", category: "Landmarks", difficulty: "MEDIUM", hint: "Tháp chuông đứng nghiêng kỳ lạ ở nước Ý", isActive: true },
  { id: uuidv4(), word: "Lâu Đài Trên Mây", category: "Landmarks", difficulty: "HARD", hint: "Tòa thành cổ tích lơ lửng giữa biển mây trắng", isActive: true },
  { id: uuidv4(), word: "Cung Điện Dưới Nước", category: "Landmarks", difficulty: "HARD", hint: "Thành phố thủy tề nguy nga bọc trong bong bóng nước", isActive: true },
  { id: uuidv4(), word: "Ngôi Nhà Cây", category: "Landmarks", difficulty: "MEDIUM", hint: "Căn chòi gỗ nhỏ dựng giữa các nhánh cây cổ thụ", isActive: true },
  { id: uuidv4(), word: "Cối Xay Gió", category: "Landmarks", difficulty: "EASY", hint: "Cánh quạt khổng lồ quay nhờ sức gió ở Hà Lan", isActive: true },
  { id: uuidv4(), word: "Cầu Vàng Bà Nà", category: "Landmarks", difficulty: "HARD", hint: "Cây cầu uốn lượn được nâng đỡ bởi hai bàn tay Phật khổng lồ", isActive: true },
  { id: uuidv4(), word: "Hang Sơn Đoòng", category: "Landmarks", difficulty: "HARD", hint: "Hang động tự nhiên lớn nhất thế giới ở Quảng Bình", isActive: true },
  { id: uuidv4(), word: "Hạ Long Bay", category: "Landmarks", difficulty: "MEDIUM", hint: "Kỳ quan với hàng ngàn đảo đá vôi nhấp nhô trên biển ngọc", isActive: true },
  { id: uuidv4(), word: "Chợ Nổi Cái Răng", category: "Landmarks", difficulty: "MEDIUM", hint: "Cảnh mua bán tấp nập thuyền bè trên sông Cần Thơ", isActive: true },
  { id: uuidv4(), word: "Lăng Bác", category: "Landmarks", difficulty: "MEDIUM", hint: "Nơi an nghỉ của Chủ tịch Hồ Chí Minh tại quảng trường Ba Đình", isActive: true },
  { id: uuidv4(), word: "Đà Lạt Ngàn Hoa", category: "Landmarks", difficulty: "MEDIUM", hint: "Thành phố sương mù với rừng thông và ngàn sắc hoa", isActive: true },
  { id: uuidv4(), word: "Ruộng Bậc Thang", category: "Landmarks", difficulty: "MEDIUM", hint: "Những đường cong màu vàng lúa chín uốn quanh sườn đồi Sa Pa", isActive: true },
  { id: uuidv4(), word: "Hồ Gươm", category: "Landmarks", difficulty: "EASY", hint: "Trái tim thủ đô với cầu Thê Húc đỏ son", isActive: true },
  { id: uuidv4(), word: "Cầu Thê Húc", category: "Landmarks", difficulty: "MEDIUM", hint: "Cây cầu màu son cong cong dẫn vào đền Ngọc Sơn", isActive: true },
  { id: uuidv4(), word: "Cố Đô Huế", category: "Landmarks", difficulty: "HARD", hint: "Hoàng thành thâm nghiêm bên bờ sông Hương thơ mộng", isActive: true },
  { id: uuidv4(), word: "Đỉnh Fansipan", category: "Landmarks", difficulty: "HARD", hint: "Nóc nhà Đông Dương sừng sững giữa biển mây trời", isActive: true },
  { id: uuidv4(), word: "Tam Cốc Bích Động", category: "Landmarks", difficulty: "MEDIUM", hint: "Thuyền trôi luồn lách qua ba hang đá núi non hùng vĩ", isActive: true },
  { id: uuidv4(), word: "Đảo Phú Quốc", category: "Landmarks", difficulty: "MEDIUM", hint: "Đảo ngọc biển xanh cát trắng nắng vàng phương Nam", isActive: true },
  { id: uuidv4(), word: "Bà Nà Hills", category: "Landmarks", difficulty: "MEDIUM", hint: "Làng Pháp thu nhỏ mát mẻ quanh năm trên đỉnh núi", isActive: true },
  { id: uuidv4(), word: "Thác Bản Giốc", category: "Landmarks", difficulty: "HARD", hint: "Thác nước tự nhiên tuyệt đẹp biên cương phương Bắc", isActive: true },
  { id: uuidv4(), word: "Tháp Chàm", category: "Landmarks", difficulty: "HARD", hint: "Kiến trúc gạch nung độc đáo của nền văn hóa Chăm-pa", isActive: true },
  { id: uuidv4(), word: "Nhà Thờ Đức Bà", category: "Landmarks", difficulty: "HARD", hint: "Nhà thờ gạch đỏ cổ kính giữa lòng thành phố Hồ Chí Minh", isActive: true },
  { id: uuidv4(), word: "Dinh Độc Lập", category: "Landmarks", difficulty: "HARD", hint: "Di tích lịch sử chứng kiến thời khắc thống nhất đất nước", isActive: true },
  { id: uuidv4(), word: "Địa Đạo Củ Chi", category: "Landmarks", difficulty: "HARD", hint: "Mê cung ngầm trong lòng đất huyền thoại trong kháng chiến", isActive: true },
  { id: uuidv4(), word: "Đảo Lý Sơn", category: "Landmarks", difficulty: "MEDIUM", hint: "Vương quốc tỏi với cổng Tò Vò trầm tích núi lửa", isActive: true },
  { id: uuidv4(), word: "Bạch Mộc Lương Tử", category: "Landmarks", difficulty: "HARD", hint: "Đỉnh núi săn mây kỳ vĩ của giới đam mê leo núi", isActive: true },
  { id: uuidv4(), word: "Đèo Mã Pí Lèng", category: "Landmarks", difficulty: "HARD", hint: "Con đèo hiểm trở đệ nhất nhìn xuống dòng sông Nho Quế xanh ngắt", isActive: true }
];

export const ACHIEVEMENTS_SEED = [
  {
    code: "ARTIST",
    name: "Danh Họa Linh Giới",
    description: "Vẽ thành công 5 lượt đoán đúng trong chế độ Draw & Guess",
    category: "DRAWING",
    rewardCoins: 250,
    rewardXp: 500,
    icon: "palette"
  },
  {
    code: "SHERLOCK",
    name: "Thám Tử Tài Ba",
    description: "Đoán đúng ẩn số chỉ trong 10 giây đầu tiên",
    category: "MYSTERY",
    rewardCoins: 300,
    rewardXp: 600,
    icon: "search"
  },
  {
    code: "SPEED_DEMON",
    name: "Phong Thần Tốc Độ",
    description: "Về đích đầu tiên trong cuộc đua Spirit Race",
    category: "RACE",
    rewardCoins: 400,
    rewardXp: 800,
    icon: "zap"
  },
  {
    code: "TRICKSTER",
    name: "Kẻ Lừa Bịp Vĩ Đại",
    description: "Lừa được trên 3 người bình chọn cho câu trả lời giả trong Bluff Mode",
    category: "BLUFF",
    rewardCoins: 350,
    rewardXp: 700,
    icon: "smile"
  },
  {
    code: "COLLECTOR",
    name: "Bậc Thầy Thu Thập",
    description: "Sở hữu ít nhất 5 Linh Thú khác nhau trong bộ sưu tập",
    category: "COLLECTION",
    rewardCoins: 500,
    rewardXp: 1000,
    icon: "box"
  },
  {
    code: "MASTER_SPIRIT",
    name: "Linh Vương Tối Cao",
    description: "Tiến hóa một Linh Thú lên cấp độ tối đa (Evolution Phase)",
    category: "PROGRESSION",
    rewardCoins: 1000,
    rewardXp: 2000,
    icon: "crown"
  }
];

export const COSMETICS_SEED = [
  // Skins
  {
    id: uuidv4(),
    name: "Hỏa Khuyển Kim Giáp",
    type: "SKIN",
    rarity: "EPIC",
    priceCoins: 600,
    assetValue: "skin-gold-armor",
    description: "Bộ giáp hoàng kim rực lửa uy nghi cho Hỏa Khuyển"
  },
  {
    id: uuidv4(),
    name: "Ảnh Miêu Hắc Ám",
    type: "SKIN",
    rarity: "RARE",
    priceCoins: 400,
    assetValue: "skin-dark-shadow",
    description: "Lớp bóng tối thuần khiết bao quanh Ảnh Miêu"
  },
  {
    id: uuidv4(),
    name: "Lôi Điểu Bão Táp",
    type: "SKIN",
    rarity: "LEGENDARY",
    priceCoins: 1200,
    assetValue: "skin-thunder-storm",
    description: "Tia sét tím phát quang liên hồi quanh sải cánh Lôi Điểu"
  },
  // Trails
  {
    id: uuidv4(),
    name: "Vết Tích Tinh Tú",
    type: "TRAIL",
    rarity: "RARE",
    priceCoins: 300,
    assetValue: "trail-starlight",
    description: "Để lại vệt sao lấp lánh khi di chuyển và nhảy trong Runner"
  },
  {
    id: uuidv4(),
    name: "Ngọn Lửa Hủy Diệt",
    type: "TRAIL",
    rarity: "EPIC",
    priceCoins: 500,
    assetValue: "trail-fire",
    description: "Lửa bốc cháy dưới chân mỗi bước chạy"
  },
  // Avatar Frames
  {
    id: uuidv4(),
    name: "Khung Rồng Vàng",
    type: "FRAME",
    rarity: "LEGENDARY",
    priceCoins: 1000,
    assetValue: "frame-dragon-gold",
    description: "Khung avatar chạm khắc Song Long Chầu Nguyệt lộng lẫy"
  },
  {
    id: uuidv4(),
    name: "Khung Hoa Sen Tinh Khiết",
    type: "FRAME",
    rarity: "COMMON",
    priceCoins: 150,
    assetValue: "frame-lotus",
    description: "Khung cánh sen hồng thanh khiết"
  },
  // Backgrounds
  {
    id: uuidv4(),
    name: "Đỉnh Núi Hoàng Hôn",
    type: "BACKGROUND",
    rarity: "RARE",
    priceCoins: 350,
    assetValue: "bg-sunset-mountain",
    description: "Hình nền hồ sơ đỉnh núi nhuộm ánh ráng chiều đỏ rực"
  },
  {
    id: uuidv4(),
    name: "Cung Điện Thần Tiên",
    type: "BACKGROUND",
    rarity: "EPIC",
    priceCoins: 700,
    assetValue: "bg-celestial-palace",
    description: "Hình nền cung đình dát vàng giữa ngàn tầng mây"
  }
];

export const SEASONAL_EVENT_SEED = {
  id: uuidv4(),
  code: "SPIRIT_GALA_2026",
  name: "Đại Hội Linh Thú Mùa Thu",
  theme: "AUTUMN_SPIRITS",
  description: "Tham gia các trận chiến vẽ, thi đoán và đường đua kỳ thú để nhận Ngọc Thu đổi vật phẩm giới hạn!",
  startDate: "2026-09-01T00:00:00Z",
  endDate: "2026-10-15T23:59:59Z",
  currencyName: "Ngọc Thu",
  isActive: true,
};

export const BATTLE_PASS_SEED = {
  id: uuidv4(),
  seasonNumber: 1,
  name: "Mùa 1: Thức Tỉnh Linh Căn",
  maxTier: 20,
  startDate: "2026-09-01T00:00:00Z",
  endDate: "2026-10-31T23:59:59Z",
  priceCoins: 800,
};
